@baseUrl = http://localhost:8400
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdEBleGFtcGxlLm9yZyIsImV4cCI6MTc2NTM2MDgzNX0._DY6b9Al5R7SVLZjYTVEvOKhU7lsi4xKqZKxxueAYE0

###
POST {{baseUrl}}/tournaments
Content-Type: application/json
accept: application/json
authorization: Bearer {{token}}

{
  "start_time": "2025-12-01T08:31:11.398Z",
  "name": "lol6",
  "dashboard_public": true,
  "dashboard_endpoint": "lol6",
  "players_can_be_in_multiple_teams": true,
  "auto_assign_courts": true,
  "duration_minutes": 1,
  "margin_minutes": 0,
  "club_id": 1
}
###
@tournamentID = 1
###
POST {{baseUrl}}/tournaments/{{tournamentID}}/stages
Content-Type: application/json
accept: application/json
authorization: Bearer {{token}}